In [2]:
import numpy as np

In [5]:
# every elem in array should be same type
n_arr = np.array([[1, 2], [3, 4]])
# minimum number of dimensions
np.array([[1, 2], [3, 4]], ndmin=3)

array([[[1, 2],
        [3, 4]]])

In [3]:
n_arr.dtype

dtype('int64')

In [4]:
print(n_arr.shape)
print(n_arr.size)

(2, 2)
4


In [5]:
# form:to:step
n_arr[:, 0]

array([1, 3])

In [6]:
n_arr[0, :]

array([1, 2])

In [7]:
# filter by expression
n_arr[n_arr>1]

array([2, 3, 4])

In [8]:
# flip array
n_arr.T
np.transpose(n_arr)

array([[1, 3],
       [2, 4]])

In [9]:
# numpy array can +-*/ a scalar
n_arr * 2 / 3 + 1 - 5 

array([[-3.33333333, -2.66666667],
       [-2.        , -1.33333333]])

In [10]:
# matrix multiplication vector*vector=scalar, matrix*matrix=matrix,matrix*vector=?
np.dot

<function numpy.core.multiarray.dot>

In [11]:
# inverse only for square matrix
square_arr = [[1,2], [3,4]]
np.linalg.inv(square_arr)
# 行列式
np.linalg.det(square_arr)

-2.0000000000000004

In [12]:
# scalar matrix whose diagonal values are 1
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [13]:
# degree 1:y=ax+b return slope,intercept
# np.polyfit(col1, col2, 1)

In [14]:
# np.nan是一个特殊的浮点数值，表示“不是数字”。在任何算术运算中，如果有参数为nan，结果都返回nan
v = np.array([1, 2, np.nan, 4, 5])
print(np.isnan(v))
ix = ~np.isnan(v)
# use array as index
v[ix]

[False False  True False False]


array([1., 2., 4., 5.])

In [15]:
np.mean(v[ix])
np.nanmean(v)

3.0

#### functions

In [16]:
# 0 for cols, 1 for rows
print(n_arr.sum(axis=0))
print(n_arr.mean())
print(n_arr.max())
print(n_arr.var())
print(n_arr.std())

[4 6]
2.5
4
1.25
1.118033988749895


In [17]:
print(np.log(n_arr))
print(np.sqrt(n_arr))
print(np.median(n_arr))

[[0.         0.69314718]
 [1.09861229 1.38629436]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
2.5


In [18]:
# get index of max value
n_arr.argmax()

3

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.random.seed(1)

In [9]:
# mean,std,size(can be tuple)
np.random.normal(5, 2, (2,4))

array([[4.67560455, 6.16546623, 4.48684868, 6.40503978],
       [1.91317859, 7.80745545, 5.65307442, 5.51164307]])

In [22]:
# from, to, size
np.random.randint(5, 19, 3)

array([18,  7,  9])

In [23]:
# rows, cols, 
np.random.rand(2,3,4)

array([[[0.4173048 , 0.55868983, 0.14038694, 0.19810149],
        [0.80074457, 0.96826158, 0.31342418, 0.69232262],
        [0.87638915, 0.89460666, 0.08504421, 0.03905478]],

       [[0.16983042, 0.8781425 , 0.09834683, 0.42110763],
        [0.95788953, 0.53316528, 0.69187711, 0.31551563],
        [0.68650093, 0.83462567, 0.01828828, 0.75014431]]])

In [24]:
np.zeros(5)
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
np.empty(6)

array([6.95199722e-310, 1.97607681e-316, 6.95199641e-310, 6.95198978e-310,
       6.95199638e-310, 6.95198978e-310])

In [10]:
# [low, high), size
np.random.uniform(0,1,5)

array([0.05061904, 0.26270603, 0.69690134, 0.13889273, 0.93819132])

In [9]:
# params can be int or array
shuffle_index=np.random.permutation(30)
print(shuffle_index)
# shuffle in place update collection
np.random.shuffle([1,2,3])

[ 7 19 25  1 26  2  9 28  6  0  3 15 12 29  4 27 22 17  5 13 23 21 24 11
 14  8 16 18 10 20]


In [28]:
# start,end,samples_num
xplot=np.linspace(1, 10, 5)
print(xplot)
# yplot=f(xplot)

[ 1.    3.25  5.5   7.75 10.  ]


In [29]:
#  cumulative product 累积
a = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(a, axis= 0, dtype=float)

array([[ 1.,  2.,  3.],
       [ 4., 10., 18.]])