In [1]:
import numpy as np

In [9]:
# every elem in array should be same type
n_arr = np.array([[1, 2], [3, 4]])

In [10]:
n_arr.dtype

dtype('int64')

In [33]:
print(n_arr.shape)
print(n_arr.size)

(2, 2)
4


In [13]:
# form:to:step
n_arr[:, 0]

array([1, 3])

In [14]:
n_arr[0, :]

array([1, 2])

In [78]:
# filter by expression
n_arr[n_arr>1]

array([2, 3, 4])

In [88]:
# flip array
n_arr.T
np.transpose(n_arr)

array([[1, 3],
       [2, 4]])

In [60]:
# numpy array can +-*/ a scalar
n_arr * 2 / 3 + 1 - 5 

array([[-3.33333333, -2.66666667],
       [-2.        , -1.33333333]])

In [79]:
# matrix multiplication vector*vector=scalar, matrix*matrix=matrix,matrix*vector=?
np.dot

<function numpy.core.multiarray.dot>

In [82]:
# inverse only for square matrix
square_arr = [[1,2], [3,4]]
np.linalg.inv(square_arr)
# 行列式
np.linalg.det(square_arr)

-2.0000000000000004

In [83]:
# scalar matrix whose diagonal values are 1
np.identity(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [89]:
# degree 1:y=ax+b return slope,intercept
# np.polyfit(col1, col2, 1)

In [74]:
# np.nan是一个特殊的浮点数值，表示“不是数字”。在任何算术运算中，如果有参数为nan，结果都返回nan
v = np.array([1, 2, np.nan, 4, 5])
print(np.isnan(v))
ix = ~np.isnan(v)
# use array as index
v[ix]

[False False  True False False]


array([ 1.,  2.,  4.,  5.])

In [76]:
np.mean(v[ix])
np.nanmean(v)

3.0

#### functions

In [32]:
# 0 for cols, 1 for rows
print(n_arr.sum(axis=0))
print(n_arr.mean())
print(n_arr.max())
print(n_arr.var())
print(n_arr.std())

2.5
4
[4 6]
1.25
1.11803398875


In [25]:
print(np.log(n_arr))
print(np.sqrt(n_arr))
print(np.median(n_arr))

[[ 0.          0.69314718]
 [ 1.09861229  1.38629436]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
2.5


In [85]:
# get index of max value
n_arr.argmax()

3

In [84]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [53]:
np.random.seed(1)

In [57]:
# mean,std,size
np.random.normal(5, 2, 10)

array([ 3.6166785 ,  4.20649295,  3.6256546 ,  3.30958872,  3.65750774,
        4.9746708 ,  2.7653793 ,  5.4688314 ,  8.31960435,  6.48408832])

In [59]:
# from, to, size
np.random.randint(5, 19, 3)

array([ 6,  6, 18])

In [52]:
# rows, cols, 
np.random.rand(2,3,4)

array([[[ 0.20508102,  1.3937333 ,  1.00889797, -0.49600541],
        [-1.40927415,  0.52732577,  0.27160782, -0.18428715],
        [-0.38032031, -1.82994678,  0.65466445, -0.10342063]],

       [[-0.31416492, -1.14807291,  0.11103814, -1.05691851],
        [-0.17429985, -1.72167843, -0.67101828, -0.83069877],
        [-0.23443035, -0.41866311, -0.49812246, -0.11716631]]])

In [43]:
np.zeros(5)
np.zeros((2, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [42]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [46]:
np.empty(6)

array([  6.91814471e-310,   6.91814471e-310,   1.32597255e-075,
         1.51925502e-047,   6.03292885e+174,   6.91791848e-310])

In [68]:
# >=low, <high, size
np.random.uniform(0,1,5)

3.222186844799221

In [92]:
# start,end,samples_num
xplot=np.linspace(1, 10, 5)
print(xplot)
# yplot=f(xplot)

[  1.     3.25   5.5    7.75  10.  ]


In [64]:
#  cumulative product 累积
a = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(a, axis= 0, dtype=float)

array([[  1.,   2.,   3.],
       [  4.,  10.,  18.]])