In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.041015  0.156557  0.969964  0.036820
2013-01-02  1.472223  0.139605  0.733998  1.532968
2013-01-03  0.816822 -1.340959  0.892377 -0.664054
2013-01-04  1.009740  0.262616  0.149544 -0.227399
2013-01-05  0.896417  0.346083  1.507956 -0.530784
2013-01-06  0.337241 -0.650551 -0.896497  0.021562

In [6]:
df2 = pd.DataFrame({ 'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [7]:
print(df2.dtypes)
print(df2.index)
print(df2.columns)
print(df2.columns[0])
print(df2.E)
print(df.values)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
Int64Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
A
0     test
1    train
2     test
3    train
Name: E, dtype: category
Categories (2, object): [test, train]
[[ 0.04101533  0.15655668  0.96996434  0.03681961]
 [ 1.47222258  0.13960484  0.73399754  1.53296803]
 [ 0.81682249 -1.34095948  0.89237691 -0.66405415]
 [ 1.00974039  0.2626156   0.14954379 -0.22739911]
 [ 0.89641671  0.34608306  1.50795632 -0.53078417]
 [ 0.33724103 -0.65055084 -0.89649744  0.02156242]]


In [9]:
#df_group=df_group.rename(columns = {'rank':'rank_avg'})

In [18]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [21]:
#transform
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.872247   -0.200392    0.942549    0.791140    0.416943    0.807785
B    0.049009   -1.160701   -1.320465   -0.883601   -0.290367   -1.239502
C   -1.153277   -1.577543    0.880961    0.062490   -0.571406   -0.037107
D   -1.079562    0.815051   -0.009976    1.935941    0.653325    0.052718

In [20]:
df.sort_index()

A         B         C         D
2013-01-01 -0.872247  0.049009 -1.153277 -1.079562
2013-01-02 -0.200392 -1.160701 -1.577543  0.815051
2013-01-03  0.942549 -1.320465  0.880961 -0.009976
2013-01-04  0.791140 -0.883601  0.062490  1.935941
2013-01-05  0.416943 -0.290367 -0.571406  0.653325
2013-01-06  0.807785 -1.239502 -0.037107  0.052718

In [22]:
df.sort_values(by='B',ascending=False)

A         B         C         D
2013-01-01 -0.872247  0.049009 -1.153277 -1.079562
2013-01-05  0.416943 -0.290367 -0.571406  0.653325
2013-01-04  0.791140 -0.883601  0.062490  1.935941
2013-01-02 -0.200392 -1.160701 -1.577543  0.815051
2013-01-06  0.807785 -1.239502 -0.037107  0.052718
2013-01-03  0.942549 -1.320465  0.880961 -0.009976

In [23]:
df.loc[dates[0]]

A   -0.872247
B    0.049009
C   -1.153277
D   -1.079562
Name: 2013-01-01 00:00:00, dtype: float64

In [24]:
df.loc[:,['B','C']]

B         C
2013-01-01  0.049009 -1.153277
2013-01-02 -1.160701 -1.577543
2013-01-03 -1.320465  0.880961
2013-01-04 -0.883601  0.062490
2013-01-05 -0.290367 -0.571406
2013-01-06 -1.239502 -0.037107

In [25]:
df.at[dates[0],'A']

-0.87224717284710673

In [26]:
df.iloc[3]

A    0.791140
B   -0.883601
C    0.062490
D    1.935941
Name: 2013-01-04 00:00:00, dtype: float64

In [27]:
df[df['A']>0]

A         B         C         D
2013-01-03  0.942549 -1.320465  0.880961 -0.009976
2013-01-04  0.791140 -0.883601  0.062490  1.935941
2013-01-05  0.416943 -0.290367 -0.571406  0.653325
2013-01-06  0.807785 -1.239502 -0.037107  0.052718

In [28]:
df[df>0]

A         B         C         D
2013-01-01       NaN  0.049009       NaN       NaN
2013-01-02       NaN       NaN       NaN  0.815051
2013-01-03  0.942549       NaN  0.880961       NaN
2013-01-04  0.791140       NaN  0.062490  1.935941
2013-01-05  0.416943       NaN       NaN  0.653325
2013-01-06  0.807785       NaN       NaN  0.052718

In [32]:
df[df['A'].isin([0.123])]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [33]:
df1=df.copy()

In [35]:
pd.isna(df1)

A      B      C      D
2013-01-01  False  False  False  False
2013-01-02  False  False  False  False
2013-01-03  False  False  False  False
2013-01-04  False  False  False  False
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False

In [ ]:
df2=df.copy()

df2.head()

pd.isna(df)

In [12]:
#read_csv('file.csv' [, index_col='col'|0] [, parse_dates=True] [, usecols=['cols']] [, na_values=['nan']])
#df = pd.read_csv(url) read csv from url
df = pd.read_csv("./loan_train.csv")
dateparse = lambda dates: pd.datetime.strptime(dates, '%Y-%m')
#data = pd.read_csv('AirPassengers.csv', parse_dates='Month', index_col='Month',date_parser=dateparse)
df.head(3)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   
1  LP001003   Male     Yes          1  Graduate            No   
2  LP001005   Male     Yes          0  Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y

### time series

In [13]:
dateparse = lambda dates: pd.datetime.strptime(dates, '%Y-%m')
data = pd.read_csv('https://www.analyticsvidhya.com/wp-content/uploads/2016/02/AirPassengers.csv', parse_dates=['Month'], index_col='Month',date_parser=dateparse)

In [14]:
data.head()

#Passengers
Month                  
1949-01-01          112
1949-02-01          118
1949-03-01          132
1949-04-01          129
1949-05-01          121

In [17]:
ts = data['#Passengers']

In [25]:
print(ts['1949-01-01'])
from datetime import datetime
print(ts[datetime(1949,1,1)])

112
112


In [30]:
#1. Specify the entire range:
print(ts['1949-01-01':'1949-05-01'])
#2. Use ':' if one of the indices is at ends:
print(ts[:'1949-05-01'])
ts['1949']


Month
1949-01-01    112
1949-02-01    118
1949-03-01    132
1949-04-01    129
1949-05-01    121
Name: #Passengers, dtype: int64
Month
1949-01-01    112
1949-02-01    118
1949-03-01    132
1949-04-01    129
1949-05-01    121
Name: #Passengers, dtype: int64


Month
1949-01-01    112
1949-02-01    118
1949-03-01    132
1949-04-01    129
1949-05-01    121
1949-06-01    135
1949-07-01    148
1949-08-01    148
1949-09-01    136
1949-10-01    119
1949-11-01    104
1949-12-01    118
Name: #Passengers, dtype: int64

In [4]:
# Load 网盟 sheet of excel file wangmeng.xlsx
df_xlsx=pd.read_excel("./wangmeng.xlsx", "网盟")

In [5]:
# Load Data from text file having tab ‘\t’ delimeter print df
df_txt=pd.read_csv(“E:/Test.txt”,sep=’\t’)

4238     卿橙
0  4235     隐逸
1  4221   掌众传媒
2  4217  盟聚DSP
3  4215     众盟
4  4210  百度信息流

In [ ]:
#save to csv
#df_txt.to_csv("my_solution_one.csv", index_label = ["PassengerId"])

In [10]:
df1=df.pivot(index= 'Loan_ID', columns='Education', values='ApplicantIncome')
df1.head()

Education  Graduate  Not Graduate
Loan_ID                          
LP001002     5849.0           NaN
LP001003     4583.0           NaN
LP001005     3000.0           NaN
LP001006        NaN        2583.0
LP001008     6000.0           NaN

In [14]:
df.sort_values(['Property_Area','ApplicantIncome'], ascending=[True, False])

Loan_ID  Gender Married Dependents     Education Self_Employed  \
409  LP002317    Male     Yes         3+      Graduate            No   
126  LP001448     NaN     Yes         3+      Graduate            No   
284  LP001922    Male     Yes          0      Graduate            No   
308  LP001996    Male      No          0      Graduate            No   
369  LP002191    Male     Yes          0      Graduate            No   
525  LP002699    Male     Yes          2      Graduate           Yes   
475  LP002527    Male     Yes          2      Graduate           Yes   
324  LP002065    Male     Yes         3+      Graduate            No   
258  LP001859    Male     Yes          0      Graduate            No   
115  LP001401    Male     Yes          1      Graduate            No   
34   LP001100    Male      No         3+      Graduate            No   
148  LP001519  Female      No          0      Graduate            No   
319  LP002050    Male     Yes          1      Graduate           Yes   
598  LP002945    Male     Yes          0      Graduate           Yes   
289  LP001935    Male      No          0      Graduate            No   
391  LP002262    Male     Yes         3+      Graduate            No   
189  LP001647    Male     Yes          0      Graduate            No   
372  LP002201    Male     Yes          2      Graduate           Yes   
390  LP002255    Male      No         3+      Graduate            No   
351  LP002140    Male      No          0      Graduate            No   
376  LP002219    Male     Yes         3+      Graduate            No   
325  LP002067    Male     Yes          1      Graduate           Yes   
196  LP001666    Male      No          0      Graduate            No   
356  LP002149    Male     Yes          2      Graduate            No   
523  LP002693    Male     Yes          2      Graduate           Yes   
441  LP002409    Male     Yes          0      Graduate            No   
309  LP001998    Male     Yes          2  Not Graduate            No   
404  LP002301  Female      No          0      Graduate           Yes   
107  LP001370    Male      No          0  Not Graduate           NaN   
444  LP002424    Male     Yes          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
282  LP001915    Male     Yes          2      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
35   LP001106    Male     Yes          0      Graduate            No   
543  LP002755    Male     Yes          1  Not Graduate            No   
220  LP001736    Male     Yes          0      Graduate            No   
117  LP001405    Male     Yes          1      Graduate            No   
437  LP002401    Male     Yes          0      Graduate            No   
406  LP002308    Male     Yes          0  Not Graduate            No   
317  LP002036    Male     Yes          0      Graduate            No   
131  LP001473    Male      No          0      Graduate            No   
299  LP001963    Male     Yes          1      Graduate            No   
305  LP001990    Male      No          0  Not Graduate            No   
451  LP002447    Male     Yes          2  Not Graduate            No   
197  LP001669  Female      No          0  Not Graduate            No   
581  LP002893    Male      No          0      Graduate            No   
338  LP002113  Female      No         3+  Not Graduate            No   
36   LP001109    Male     Yes          0      Graduate            No   
422  LP002361    Male     Yes          0      Graduate            No   
283  LP001917  Female      No          0      Graduate            No   
249  LP001825    Male     Yes          0      Graduate            No   
41   LP001120    Male      No          0      Graduate            No   
300  LP001964    Male     Yes          0  Not Graduate            No   
303  LP001977    Male     Yes          1      Graduate            No   
417  LP002342    Male     Yes          2      

In [15]:
df.sort_index(ascending=False)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
613  LP002990  Female      No          0      Graduate           Yes   
612  LP002984    Male     Yes          2      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
609  LP002978  Female      No          0      Graduate            No   
608  LP002974    Male     Yes          0      Graduate            No   
607  LP002964    Male     Yes          2  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
602  LP002953    Male     Yes         3+      Graduate            No   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
600  LP002949  Female      No         3+      Graduate           NaN   
599  LP002948    Male     Yes          2      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
592  LP002933     NaN      No         3+      Graduate           Yes   
591  LP002931    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
588  LP002925     NaN      No          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
584  LP002911    Male     Yes          1      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
29   LP001087  Female      No          2      Graduate           NaN   
28   LP001086    Male      No          0  Not Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
26   LP001068    Male     Yes          0      Graduate            No   
25   LP001066    Male     Yes          0      Graduate           Yes   
24   LP001052    Male     Yes          1      Graduate           NaN   
23   LP001050     NaN     Yes          2  Not Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
20   LP001043    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
18   LP001038    Male     Yes          0  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
12   LP001028    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
10   LP001024    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
7    LP001014    Male     Yes         3+      Graduate            No   
6    LP001013    Male     Yes          0  Not 

In [29]:
#df.groupby('col'|['cols'],as_index=False).mean()
group=df.groupby(['Gender','Education'])
group.describe()

ApplicantIncome                                            \
                              count         mean          std     min     25%   
Gender Education                                                                
Female Graduate                92.0  4646.467391  3317.369895   416.0  2894.0   
       Not Graduate            20.0  4629.700000  4732.008432   210.0  2102.5   
Male   Graduate               376.0  5992.345745  6921.455587   150.0  3032.0   
       Not Graduate           113.0  3630.061947  1411.070435  1442.0  2600.0   

                                             CoapplicantIncome               \
                        50%     75%      max             count         mean   
Gender Education                                                              
Female Graduate      3638.5  4622.5  19484.0              92.0  1231.206522   
       Not Graduate  3208.5  4457.5  18165.0              20.0   541.300000   
Male   Graduate      4166.0  6250.0  81000.0             376.0  1845.691277   
       Not Graduate  3357.0  4288.0   7667.0             113.0  1401.008850   

                     ...   LoanAmount        Loan_Amount_Term              \
                     ...          75%    max            count        mean   
Gender Education     ...                                                    
Female Graduate      ...       138.75  600.0             91.0  350.769231   
       Not Graduate  ...       128.50  225.0             18.0  360.000000   
Male   Graduate      ...       184.50  650.0            369.0  343.317073   
       Not Graduate  ...       134.00  279.0            109.0  327.302752   

                                                                   
                           std    min    25%    50%    75%    max  
Gender Education                                                   
Female Graduate      62.021336   36.0  360.0  360.0  360.0  480.0  
       Not Graduate   0.000000  360.0  360.0  360.0  360.0  360.0  
Male   Graduate      61.417404   12.0  360.0  360.0  360.0  480.0  
       Not Graduate  82.621572   36.0  360.0  360.0  360.0  480.0  

[4 rows x 40 columns]

In [30]:
group.size()

Gender  Education   
Female  Graduate         92
        Not Graduate     20
Male    Graduate        376
        Not Graduate    113
dtype: int64

In [26]:
#gen sample Data set
import numpy as np
from random import sample
rindex = np.array(sample(range(len(df)), 3))
sample = df.iloc[rindex]
sample

Loan_ID Gender Married Dependents Education Self_Employed  \
43   LP001131   Male     Yes          0  Graduate            No   
431  LP002379   Male      No          0  Graduate            No   
218  LP001732   Male     Yes          2  Graduate           NaN   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
43              3941             2336.0       134.0             360.0   
431             6500                0.0       105.0             360.0   
218             5000                0.0        72.0             360.0   

     Credit_History Property_Area Loan_Status  
43              1.0     Semiurban           Y  
431             0.0         Rural           N  
218             0.0     Semiurban           N

In [28]:
#drop_duplicates
rem_dup=df.drop_duplicates(['Gender', 'Education'])
rem_dup

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
3    LP001006    Male     Yes          0  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
50   LP001155  Female     Yes          0  Not Graduate            No   
126  LP001448     NaN     Yes         3+      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
3               2583             2358.0       120.0             360.0   
17              3510                0.0        76.0             360.0   
23              3365             1917.0       112.0             360.0   
50              1928             1644.0       100.0             360.0   
126            23803                0.0       370.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
3               1.0         Urban           Y  
17              0.0         Urban           N  
23              0.0         Rural           N  
50              1.0     Semiurban           Y  
126             1.0         Rural           Y

In [33]:
df.isnull()
df.isnull().any()

Loan_ID              False
Gender                True
Married               True
Dependents            True
Education            False
Self_Employed         True
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount            True
Loan_Amount_Term      True
Credit_History        True
Property_Area        False
Loan_Status          False
dtype: bool

In [ ]:
#df.fillna(value,method='ffill|bfill' ,inplace=True|False)

In [8]:
#join two dataframes return new df, left_on:left side col, right_index:right side use index to join
#df1.merge(df2,how=['inner|left|right'],on=['cols'],left_on=[],right_on=[],right_index=True|False)

In [40]:
df[['A','C']]

KeyError: ('A', 'C')

In [ ]:
#normalize by devide by first row to compare diff dataset
df/df.ix[0,:]

In [ ]:
#bollinger_bands
rm=pd.rolling_mean(df['col'],window=20)
rstd=pd.rolling_std(df['col'],window=20)
rm+rstd*1.96,rm-rstd*1.96

In [ ]:
#daily return (p[t]/p[t-1])-1
#mean of daily return indicates totals trends
daily_returns=(df/df.shift(1))-1
#method 2
#daily_returns=df.copy()
#daily_returns[1:]=(df[1:]/df[:-1].values)-1
daily_returns.ix[0,:]=0

In [ ]:
#Cumulative Returns (p[t]/p[0])-1


In [ ]:
#sharp ratio ,evaluate return with risk
#risk free rate =(LIBOR,3month 债券利率,0,用年利率计算)
#k=sample frequency per year, daily=sqrt(年交易天数＝252), weekly=sqrt(52), monthly=sqrt(12)
sqrt(252)*mean(daily_return-daily_rfr)/std(daily_return-daily_rfr)