In [1]:
from sklearn.datasets import load_boston
boston = load_boston()

/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.data[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


## Requirements for working with data in scikit-learn
- Features and response are separate objects
- Features and response should be numeric
- Features and response should be NumPy arrays
- Features and response should have specific shapes

In [6]:
print(type(iris.data))
print(type(iris.target))
print(iris.data.shape)
print(iris.target.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(150, 4)
(150,)


In [45]:
# store feature matrix(uppercase) in "X"
X = iris.data
# store response vector(lowercase) in "y"
y = iris.target
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=3)

/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


### Logistic Regression

In [9]:
# It is used to predict a binary outcome (1 / 0, Yes / No, True / False) given a set of independent variables.
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

In [10]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred)

0.93333333333333335

### confusion matrix
- **True Positives (TP):** we *correctly* predicted that they *do* have diabetes
- **True Negatives (TN):** we *correctly* predicted that they *don't* have diabetes
- **False Positives (FP):** we *incorrectly* predicted that they *do* have diabetes (a "Type I error")
- **False Negatives (FN):** we *incorrectly* predicted that they *don't* have diabetes (a "Type II error")

In [11]:
confusion = metrics.confusion_matrix(y_test, y_pred)
print(confusion)

[[22  0  0]
 [ 0 16  4]
 [ 0  0 18]]


/usr/lib/python3/dist-packages/scipy/sparse/coo.py:200: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.row) != 1 or np.rank(self.col) != 1:


In [12]:
#Classification Accuracy
TPTN=confusion[0,0]+confusion[1,1]+confusion[2,2]
print(TPTN/len(y_test))

0.933333333333


In [13]:
#Classification Error: Overall, how often is the classifier incorrect?
print(1 - metrics.accuracy_score(y_test, y_pred))

0.0666666666667


In [14]:
#Sensitivity: When the actual value is positive, how often is the prediction correct?
#Also known as "True Positive Rate" or "Recall"
#print(TP / float(TP + FN))
print(metrics.recall_score(y_test, y_pred,average='micro'))
#Specificity: When the actual value is negative, how often is the prediction correct?
#print(TN / float(TN + FP))
#False Positive Rate: When the actual value is negative, how often is the prediction incorrect?
#print(FP / float(TN + FP))
#Precision: When a positive value is predicted, how often is the prediction correct?
#print(TP / float(TP + FP))
print(metrics.precision_score(y_test, y_pred,average='micro'))

0.933333333333
0.933333333333


In [15]:
## print the first 10 predicted probabilities of class membership
print(logreg.predict(X_test)[:10])
logreg.predict_proba(X_test)[0:10]

[0 0 0 0 0 2 1 0 2 1]


array([[  8.28593451e-01,   1.71253164e-01,   1.53385606e-04],
       [  8.06825879e-01,   1.92952188e-01,   2.21932724e-04],
       [  8.44530320e-01,   1.55400872e-01,   6.88076658e-05],
       [  7.69653968e-01,   2.30166546e-01,   1.79485479e-04],
       [  9.42039172e-01,   5.79499546e-02,   1.08729492e-05],
       [  3.75345657e-05,   3.87358762e-01,   6.12603703e-01],
       [  2.70186378e-02,   5.91172569e-01,   3.81808794e-01],
       [  8.64777392e-01,   1.35080856e-01,   1.41752170e-04],
       [  9.27560202e-04,   3.21755793e-01,   6.77316647e-01],
       [  5.77240721e-02,   7.63138090e-01,   1.79137838e-01]])

In [16]:
# store the predicted probabilities for class 1
y_pred_prob = logreg.predict_proba(X_test)[:, 1]
print(y_pred_prob[:10])

[ 0.17125316  0.19295219  0.15540087  0.23016655  0.05794995  0.38735876
  0.59117257  0.13508086  0.32175579  0.76313809]


In [17]:
# predict diabetes if the predicted probability is greater than 0.3
from sklearn.preprocessing import binarize
y_pred_class = binarize([y_pred_prob], 0.3)[0]
print(y_pred_class[:10])

[ 0.  0.  0.  0.  0.  1.  1.  0.  1.  1.]


## ROC Curves and Area Under the Curve (AUC)

### knn

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

In [19]:
#disp default params
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [20]:
for i in range(1,26):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    print(i,metrics.accuracy_score(y_test,y_pred))

1 0.966666666667
2 0.966666666667
3 0.95
4 0.95
5 0.933333333333
6 0.95
7 0.95
8 0.95
9 0.95
10 0.933333333333
11 0.933333333333
12 0.95
13 0.966666666667
14 0.966666666667
15 0.966666666667
16 0.95
17 0.966666666667
18 0.95
19 0.95
20 0.95
21 0.95
22 0.933333333333
23 0.933333333333
24 0.95
25 0.966666666667


In [1]:
import pandas as pd
data = pd.read_csv('http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv', index_col=0)
data.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [2]:
feature_cols = ['TV', 'radio', 'newspaper']
X = data[feature_cols]
y = data['sales']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [10]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>


In [6]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
# print the intercept and coefficients
print(linreg.intercept_)
print(linreg.coef_)
# pair the feature names with the coefficients
list(zip(feature_cols, linreg.coef_))

2.8769666223179318
[0.04656457 0.17915812 0.00345046]


[('TV', 0.04656456787415028),
 ('radio', 0.17915812245088836),
 ('newspaper', 0.0034504647111804347)]

$$y = 2.88 + 0.0466 \times TV + 0.179 \times Radio + 0.00345 \times Newspaper$$

In [8]:
y_pred = linreg.predict(X_test)

In [27]:
import numpy as np

**Mean Absolute Error** (MAE) is the mean of the absolute value of the errors:
$$\frac 1n\sum_{i=1}^n|y_i-\hat{y}_i|$$
**Mean Squared Error** (MSE) is the mean of the squared errors:
$$\frac 1n\sum_{i=1}^n(y_i-\hat{y}_i)^2$$
**Root Mean Squared Error** (RMSE) is the square root of the mean of the squared errors:
$$\sqrt{\frac 1n\sum_{i=1}^n(y_i-\hat{y}_i)^2}$$

In [28]:
print(metrics.mean_absolute_error(y_test, y_pred))
print(metrics.mean_squared_error(y_test, y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

1.06689170826
1.97304562023
1.40465142303


### K-fold cross-validation

In [44]:
from sklearn.model_selection import cross_val_score

In [46]:
#use iris dataset
knn = KNeighborsClassifier(n_neighbors=5)

scores = cross_val_score(knn, X, y, cv=10, scoring='accuracy')
print(scores)
# use average accuracy as an estimate of out-of-sample accuracy
print(scores.mean())

[ 1.          0.93333333  1.          1.          0.86666667  0.93333333
  0.93333333  1.          1.          1.        ]
0.966666666667


In [80]:
# 10-fold cross-validation with K from 1 to 31 for KNN (the n_neighbors parameter)
# for finance data using roll forward cross validation,keep train data ahead of test data
k_range = list(range(1, 31))
k_scores = []
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X, y, cv=10, scoring='accuracy')
    k_scores.append(scores.mean())
print(k_scores)

[0.95999999999999996, 0.95333333333333337, 0.96666666666666656, 0.96666666666666656, 0.96666666666666679, 0.96666666666666679, 0.96666666666666679, 0.96666666666666679, 0.97333333333333338, 0.96666666666666679, 0.96666666666666679, 0.97333333333333338, 0.98000000000000009, 0.97333333333333338, 0.97333333333333338, 0.97333333333333338, 0.97333333333333338, 0.98000000000000009, 0.97333333333333338, 0.98000000000000009, 0.96666666666666656, 0.96666666666666656, 0.97333333333333338, 0.95999999999999996, 0.96666666666666656, 0.95999999999999996, 0.96666666666666656, 0.95333333333333337, 0.95333333333333337, 0.95333333333333337]


In [81]:
# find top 3 best perf
#top=sorted(range(1,len(k_scores)),key=lambda x:k_scores[x-1],reverse=True)[0:3]
np_k_scores=np.array(k_scores)
top_index=np_k_scores.argsort()[::-1][:3]
print(top_index+1)
print(np_k_scores[[top_index]])

[13, 18, 20]

In [104]:
# 10-fold cross-validation with logistic regression
logreg = LogisticRegression()
print(cross_val_score(logreg, X, y, cv=10, scoring='accuracy').mean())

0.953333333333


In [111]:
# 10-fold cross-validation with all three features
lm = LinearRegression()
print(np.sqrt(-cross_val_score(lm, X, y, cv=10, scoring='mean_squared_error')).mean())
compare with 2 features
X1 = data[['TV', 'radio']]
print(np.sqrt(-cross_val_score(lm, X1, y, cv=10, scoring='mean_squared_error')).mean())

1.69135317081
1.67967484191


#### grid search

In [1]:
param_grid = dict(n_neighbors=list(range(1,31)),weights = ['uniform', 'distance'])

In [2]:
param_grid

{'n_neighbors': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30],
 'weights': ['uniform', 'distance']}

In [29]:
print(param_grid)

{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], 'weight_options': ['uniform', 'distance']}


In [9]:
knn = KNeighborsClassifier()

In [32]:
from sklearn.grid_search import GridSearchCV
grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')
grid.fit(X,y)

GridSearchCV(cv=10, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], 'weights': ['uniform', 'distance']},
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=0)

In [33]:
grid.grid_scores_
print(grid.best_score_)
print(grid.best_params_)
print(grid.best_estimator_)

0.98
{'n_neighbors': 13, 'weights': 'uniform'}
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=13, p=2,
           weights='uniform')


In [35]:
# train your model using all data and the best known parameters
knn = KNeighborsClassifier(n_neighbors=13, weights='uniform')
knn.fit(X, y)
# make a prediction on out-of-sample data
knn.predict([[3, 5, 4, 2]])

array([1])

In [36]:
# shortcut: GridSearchCV automatically refits the best model using all of the data
grid.predict([[3, 5, 4, 2]])

array([1])

In [37]:
from sklearn.grid_search import RandomizedSearchCV
rand = RandomizedSearchCV(knn, param_grid, cv=10, scoring='accuracy', n_iter=10, random_state=5)
rand.fit(X, y)

RandomizedSearchCV(cv=10, error_score='raise',
          estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=13, p=2,
           weights='uniform'),
          fit_params={}, iid=True, n_iter=10, n_jobs=1,
          param_distributions={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], 'weights': ['uniform', 'distance']},
          pre_dispatch='2*n_jobs', random_state=5, refit=True,
          scoring='accuracy', verbose=0)

In [38]:
rand.grid_scores_

[mean: 0.97333, std: 0.03266, params: {'n_neighbors': 16, 'weights': 'distance'},
 mean: 0.96667, std: 0.03333, params: {'n_neighbors': 22, 'weights': 'uniform'},
 mean: 0.98000, std: 0.03055, params: {'n_neighbors': 18, 'weights': 'uniform'},
 mean: 0.96667, std: 0.04472, params: {'n_neighbors': 27, 'weights': 'uniform'},
 mean: 0.95333, std: 0.04269, params: {'n_neighbors': 29, 'weights': 'uniform'},
 mean: 0.97333, std: 0.03266, params: {'n_neighbors': 10, 'weights': 'distance'},
 mean: 0.96667, std: 0.04472, params: {'n_neighbors': 22, 'weights': 'distance'},
 mean: 0.97333, std: 0.04422, params: {'n_neighbors': 14, 'weights': 'uniform'},
 mean: 0.97333, std: 0.04422, params: {'n_neighbors': 12, 'weights': 'distance'},
 mean: 0.97333, std: 0.03266, params: {'n_neighbors': 15, 'weights': 'uniform'}]

In [39]:
print(rand.best_score_)
print(rand.best_params_)

0.98
{'n_neighbors': 18, 'weights': 'uniform'}


### Decision tree

In [41]:
from sklearn.tree import tree

In [42]:
my_tree=tree.DecisionTreeClassifier(max_depth = 10,min_samples_split =5)

In [ ]:
# Create the target and features numpy arrays: target, features
target = train['Survived'].values
features = train[["Pclass", "Sex", "Age", "Fare"]].values

my_tree = my_tree.fit(features, target)

In [ ]:
# Look at the importance and score of the included features
print(my_tree.feature_importances_)
print(my_tree.score(features, target))

### random forest

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
forest = RandomForestClassifier(max_depth = 10, min_samples_split=2, n_estimators = 100, random_state = 1)

In [ ]:
my_forest = forest.fit(features_forest, target)
my_forest.score(features_forest, target)

#### pipeline

In [46]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
number = LabelEncoder()
train['Married_new'] = number.fit_transform(train['Married'].astype(str))
number.inverse_transform(predicted)